version: "3.8"
services:
  django-backend:
    image: cheapify-django-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/db.sqlite3:/usr/src/app/db.sqlite3
    ports:
      - "8000:8000"
  react-frontend:
    image: cheapify-react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"